export const scheduleDailyReminder = jest.fn();
export const sendTiltNotification = jest.fn();
export const registerBetResultCategory = jest.fn();
export const scheduleBetResultReminder = jest.fn();
export const cancelBetResultReminder = jest.fn();
export const cancelAllBetResultReminders = jest.fn();
export const requestNotificationPermission = jest.fn(async () => true);
export const BET_RESULT_CATEGORY = 'bet_result';
export const dismissBetResultNotification = jest.fn();
export const syncBetResultReminders = jest.fn();
export const setBetPendingResolver = jest.fn();
